name: Build
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Deploy Documentation
    runs-on: [self-hosted]
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
      - name: Set up Python 3.9 s v
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Mkdocs
        run: pip install -r ./.devcontainer/docs-requirements.txt

      - name: Set Git user
        run: git config user.name ci-bot

      - name: Set Git email
        run: git config user.email patrick.mclean@sap.com

      - name: Get Latest
        run: git pull

      - name: Build the Docs site
        run: bash .github/deploy.sh
